[[plugin]]
id = "jubii/timer"
name = "Timer"
version = "1.0.0"
author = "jubii"
dependencies = ["libpulse"]
license = "MIT"
icon = "clock"
description = "A timer + stopwatch desktop widget with start/pause, reset, and timer adjustment buttons."
min_noctalia = "5.0.0"
tags = ["timer", "desktop", "productivity"]

[[plugin]]
id = "jubii/color-picker"
name = "Color Picker"
version = "1.0.0"
author = "jubii"
dependencies = ["hyprpicker"]
license = "MIT"
icon = "color-picker"
description = "Color picker bar widget - supports multiple color formats. Depends on hyprpicker."
min_noctalia = "5.0.0"
tags = ["tool", "productivity"]
